name: Build and deploy
on: [push]

jobs:
  azurelogin:
    name: Azure Login
    runs-on: windows-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  theme1:
    needs: azurelogin
    name: Theme 1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check environment variables
      env:
        BRANCH: ${{ GitVersion_BranchName }}
      run: echo This branch is $BRANCH