name: Build and deploy

on: [push]

jobs:
#   azurelogin:
#     name: Azure Login
#     runs-on: ubuntu-latest
#     steps:
#     - name: Azure Login
#       uses: azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }}
  theme1:
    # needs: azurelogin
    name: Theme 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-setup-dotnet@v1
    - uses: actions/setup-gitversion@v1.0.0
      with: 
        gitversion-version: 5.1.1
    - name: Check environment variables
      run: echo GitVersion branch $GitVersion_BranchName