name: Build and deploy

on: [push]

jobs:
  azurelogin:
    name: Azure Login
    runs-on: windows-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}