name: Build and deploy
on: [push]

env:
  BOB: Bob is here

jobs:
  theme1:
    name: Theme 1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check environment variables
      run: |
        echo Env variable is $Env:BOB
        echo Reference is $Env:GITHUB_REF

    - name: Set Node.js 12.x
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Install
      run: npm install

    - name: Build
      run: npm run theme1

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Deploy
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch -s dist -d \$web --account-name payexdesignguide