name: Feature or develop
on: 
  push:
    branches:
      - "feature/**"
      - "develop"

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ["payex", "swedbankpay"]
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/checkout@v1

      # Set brand specific variables
      - name: Environment variables
        run: |
          chmod +x ./.github/scripts/script.sh
          ./.github/scripts/script.sh
        env:
          BRAND: ${{ matrix.brand }}

      - name: Print variables
        run: |
          echo $BRAND_URL
          echo $BRAND_BUILD_SCRIPT

      - name: Fetch tags and master for GitVersion
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master

      - name: Install GitVersion
        uses: gittools/actions/setup-gitversion@v0.3
        with:
          versionSpec: '5.1.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/execute-gitversion@v0.3

      - name: Set Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run $BRAND_BUILD_SCRIPT -- --env.baseUrl="$BRAND_URL" --env.basename=${{ steps.gitversion.outputs.branchName }} --env.semver=${{ steps.gitversion.outputs.semVer }}--env.info_version=${{ steps.gitversion.outputs.informationalVersion }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -s dist -d \$web --account-name ${{ matrix.brand }}designguide