# This janitor cleans up feature folders where the branches have been deleted
name: Janitor
on:
  schedule:
    # This janitor will now run every night
    # - cron:  '0 0 * * *'

    # Testing purposes, runs every two minute
    - cron: "*/5 * * * *"

jobs:
  janitor:
    name: Janitor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Janitor doing janitor things..."
          chmod +x ./.github/scripts/janitor.sh
          ./.github/scripts/janitor.sh