# This janitor cleans up feature folders where the branches have been deleted
name: Janitor
on:
  schedule:
    # This janitor will now run every night
    - cron:  '0 0 * * *'

jobs:
  janitor:
    name: Janitor
    runs-on: ubuntu-latest
    steps:
      - run: echo Janitor should be cleaning now
