name: Janitor
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    name: Hello world
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ["payex", "swedbankpay"]
    steps:
        # Set brand specific variables
      - name: Environment variables
        id: variables
        run: ./.github/scripts/variables.sh
        env:
          BRAND: ${{ matrix.brand }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Azure Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch -s $web --pattern feature/test --account-name ${{ steps.variables.outputs.AZURE_ACCOUNT }}