# This janitor cleans up feature folders where the branches have been deleted
name: Janitor
on:
  schedule:
    # This janitor will now run every night
    # - cron:  '0 0 * * *'

    # Testing purposes
    - cron: "*/2 * * * *"

jobs:
  janitor:
    name: Janitor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: echo Janitor should be cleaning now
      - run: ./.github/scripts/janitor.sh
