name: Master
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ["payex", "swedbankpay"]
    steps:
      - uses: actions/checkout@v2

      # Set brand specific variables
      - name: Environment variables
        run: |
          chmod +x ./.github/scripts/variables.sh
          ./.github/scripts/variables.sh
        env:
          BRAND: ${{ matrix.brand }}

      # Add sentry token
      - name: Sentry token
        run: |
          chmod +x ./.github/scripts/sentry.sh
          ./.github/scripts/sentry.sh
        env:
          TOKEN: ${{ secrets.SENTRY_TOKEN }}
      
      - name: Fetch tags and master for GitVersion
        run: |
          git fetch --tags
          git branch --create-reflog master origin/master
      - name: Install GitVersion
        uses: gittools/actions/setup-gitversion@v0.6.1
        with:
          versionSpec: '5.1.x'
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/execute-gitversion@v0.6.1

      - name: Set Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci # <-- Node gyp fails on "npm ci" for some reason

      - name: Build
        run: npm run $BRAND_BUILD_SCRIPT -- --env.release=true --env.baseUrl="$BRAND_URL" --env.basename="v/${{ steps.gitversion.outputs.majorMinorPatch }}" --env.semver=${{ steps.gitversion.outputs.semVer }} --env.info_version=${{ steps.gitversion.outputs.informationalVersion }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Deploy
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -s dist -d \$web --account-name ${{ matrix.brand }}designguide