name: Build pull request
on: [pull_request]

jobs:
  payex:
    name: PayEx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build:prod:payex